export default async function Revenue() {
  return (
    <div>
      <h1>Revenue Page</h1>
      <p>This page provides insights into the revenue generated by the business.</p>
      <ul>
        <li><a href="/revenue/overview">Overview</a></li>
        <li><a href="/revenue/analytics">Analytics</a></li>
        <li><a href="/revenue/reports">Reports</a></li>
      </ul>
    </div>
  );
}